tg: https://t.me/lepekhinstudio
vk: https://vk.com/lepekhinstudio
bh: https://www.behance.net/lepekhinstudio
email: hello@lepekhin.studio
tel: +7 950 499-59-90
name: Студия Евгения Лепёхина
policy: https://docs.google.com/document/d/1pVJAbN8KmAKf5PvjB85avqBVZGQ_yq1aMDNdjJ66eUo/edit?usp=sharing
email_label: на письма отвечают Александра и Евгений
tel_label: звонки принимает Евгений, арт-директор студии
requisites:  https://elba.kontur.ru/card/lepekhin
questions_first_meeting: https://docs.google.com/document/d/1J6alQXdEyYvrMZE0D4ZM89HRD_vojLWwmqHTAGJUQXc/edit
contract:  #
mailing:  #